### ISSUE TITLE
Unable to compile the code as Config_unet_Pancreas.py file not found

### ISSUE THREAD

**Issue by ramesh-kumar-l** [MIC-DKFZ/basic_unet_example#2]
Hi MIC-DKFZ Team ,
   I am unable to compile the code , because of below error 
-------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "run_train_pipeline.py", line 24, in <module>
    from configs.Config_unet_Pancreas import get_config
ModuleNotFoundError: No module named 'configs.Config_unet_Pancreas'
-------------------------------------------------------------------------------------

I request you to please update all the dependency files needed for compiling the code.
Thanks

**Comment by elpequeno** [comment]
Hi ramesh,

thank you for that hint. that was my mistake, I included a config file that I never committed. That was meant to be for local testing. I corrected it. Could you please pull and try again?

Cheers, 
André

**Comment by RuiruiKang** [comment]
I am still facing the same issue with similar error
Traceback (most recent call last):
  File "run_train_pipeline.py", line 24, in <module>
    from configs.Config_unet import get_config
  File "/home/basic_unet_example/configs/Config_unet.py", line 20, in <module>
    from trixi.util import Config
ModuleNotFoundError: No module named 'trixi'

 how to solve this problem in detail?
although I have already pip install trixi successfully

**Comment by elpequeno** [comment]
Dear RuiruiKang,

can you open a terminal with your python env and just try "python -c "import trixi"". What does it say?
can you import "from trixi.util import Config" in your terminal?

**Comment by elpequeno** [comment]
I have not heard back from you in a while. Is this issue solved?

**Comment by elpequeno** [comment]
I assume this issue is solved. If not, please open a new one.
